export { initQitsIntegration } from './lib/init-qits-integration';
export type { QitsIntegrationOptions } from './lib/init-qits-integration';
export { provideQitsIntegration } from './lib/provide-qits-integration';
export type { QitsIntegrationFeature } from './lib/provide-qits-integration';
export { withFeatureCapture } from './lib/with-feature-capture';
export type { CaptureFeatureOptions } from './lib/capture-config';
export { captureNow } from './lib/capture-now';
export type { CaptureResult } from './lib/capture-now';
export { freezeDocument, freezeElement } from './lib/document-freeze';
export type { FrozenDocument } from './lib/document-freeze';
export { pickElement } from './lib/element-picker';
export { nearestAppComponent } from './lib/app-component';
export type { CaptureSelection } from './lib/capture-payload';
export { withQitsSnapshot } from './lib/with-qits-snapshot';
export { registerCaptureState } from './lib/capture-state';
export type { CaptureStateSupplier } from './lib/capture-state';
