export { initQitsIntegration } from './lib/init-qits-integration';
export type { QitsIntegrationOptions } from './lib/init-qits-integration';
export { provideQitsIntegration } from './lib/provide-qits-integration';
export type { QitsIntegrationFeature } from './lib/provide-qits-integration';
export { withFeatureCapture } from './lib/with-feature-capture';
export type { CaptureFeatureOptions } from './lib/capture-config';
export { captureNow } from './lib/capture-now';
export type { CaptureResult } from './lib/capture-now';
export { freezeDocument } from './lib/document-freeze';
export type { FrozenDocument } from './lib/document-freeze';
